<script lang="ts">
	import Icon from '$lib/Components/Icon.svelte';
	import YoutubeIcon from '~icons/logos/youtube-icon';
	import { getDrawerStore } from '@skeletonlabs/skeleton';
	import { onMount } from 'svelte';

	let drawerStore = getDrawerStore();
	onMount(() => {
		drawerStore.close();
	});
</script>

<div
	class="absolute bg-surface-900-token w-full min-h-full max-h-fit flex flex-col items-center space-y-8 p-4"
>
	<div class="flex flex-row w-full relative justify-center items-center">
		<div class="flex-1 flex flex-col left-0 justify-center items-center">
			<h1 class="h1 text-center text-primary-500">About</h1>
		</div>
	</div>
	<article class="w-full h-full prose text-on-surface-token">
		<p>
			On February 25th, 2025, <a href="https://www.youtube.com/@GMTK" class="!text-on-surface-token"
				><u class="!underline-offset-2 !decoration-2 !decoration-primary-500"
					>Mark Brown from Game Maker's Toolkit</u
				></a
			> uploaded the following video...
		</p>
		<div class="flex flex-row w-full justify-center">
			<iframe
				class="aspect-video"
				src="https://www.youtube-nocookie.com/embed/0m60QbT85Tc?si=MCDnyVqz4aGggRrT"
				style="width: 100%; height: 100%"
				title="YouTube video player"
				frameborder="0"
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
				referrerpolicy="strict-origin-when-cross-origin"
				allowfullscreen
			></iframe>
		</div>
		<p>
			...in which he briefly displays a hypothetical "periodic table of game mechanics". The idea
			was really cool, and I saw some others who thought the same, like <a
				href="https://www.youtube.com/@MrEnvisioner"
				class="!text-on-surface-token"
				><u class="!underline-offset-2 !decoration-2 !decoration-primary-500">@Mr Envisioner</u></a
			>. I had a rudimentary idea on how to build it, so I tried. This is the result, a very hastily
			put-together prototype.
		</p>
		<img class="border border-primary-500 rounded-lg my-0" src="periodic_table_gmtk.png" />
		<p class="text-right w-full text-xs">
			Credit: <YoutubeIcon class="inline mx-1" /><a
				href="https://wikipedia.org/wiki/Game_mechanics"
				class="!text-on-surface-token !decoration-primary-500 !underline-offset-2 !decoration-2"
				>Game Maker's Toolkit</a
			>
		</p>

		<h2 class="h2 text-primary-500">Using Mechdex</h2>
		<p>
			Mechdex is short for "mechanics index". It organizes modular, atomic <a
				href="https://wikipedia.org/wiki/Game_mechanics"
				class="!text-on-surface-token"
				><u class="!underline-offset-2 !decoration-2 !decoration-primary-500">game mechanics</u></a
			>, primarily those of video games. They're organised into 22 categories and are all
			searchable. Anyone can contribute to this database (see <i>Contributing a Mechanic</i>).
		</p>
		<p>
			The idea is that when you're stuck on a design problem, you can come here for inspiration, and
			to see what other designers did, how they solved it, and how well it worked.
		</p>
		<h2 class="h2 text-primary-500">This Is Very Scrappy</h2>
		<p>
			This project was made in two evenings by an absolute amateur. It's very minimal for now. This
			is not the final product. Please don't verbally abuse me. Thank you.
		</p>
		<p>
			Also, yes, the initial mechanics data was generated by AI. I'm very, very sorry to have had to
			do this, but there's no way I could write placeholders for 22x5 = 110 mechanics myself. These
			will be slowly phased out for human-written content. In the mean time, if you'd like to
			improve them, please do so!
		</p>
		<h2 class="h2 text-primary-500">Contributing a Mechanic</h2>
		<p>
			The entire database is stored in a Github repository. That's also why everything loads so
			slowly. Plans will eventually be made to move to better infrastructure.
		</p>
		<p>
			To contribute, go to the <a
				href="https://github.com/Mechdex/mechanics"
				class="!text-on-surface-token"
				><u class="!underline-offset-2 !decoration-2 !decoration-primary-500"
					>the Github repository</u
				></a
			> and read the README.md file there. You have to open a pull request to add a mechanic.
		</p>
	</article>
</div>
