<script lang="ts">
	import Icon from '$lib/Components/Icon.svelte';
	import YoutubeIcon from '~icons/logos/youtube-icon';
	import { getDrawerStore } from '@skeletonlabs/skeleton';
	import { onMount } from 'svelte';

	import HammerWrenchIcon from '~icons/mdi/hammer-wrench';
	let drawerStore = getDrawerStore();
	onMount(() => {
		drawerStore.close();
	});
</script>

<div
	class="bg-surface-900-token flex max-h-fit min-h-full w-full flex-col items-center space-y-8 p-4"
>
	<div class="relative flex w-full flex-row items-center justify-center">
		<div class="left-0 flex flex-1 flex-col items-center justify-center">
			<h1 class="h1 text-center text-primary-500">About</h1>
		</div>
	</div>
	<article class="prose h-full w-full text-on-surface-token sm:pb-10">
		<p>
			On February 25th, 2025, <a href="https://www.youtube.com/@GMTK" class="!text-on-surface-token"
				><u class="!decoration-primary-500 !decoration-2 !underline-offset-2"
					>Mark Brown from Game Maker's Toolkit</u
				></a
			> uploaded the following video...
		</p>
		<div class="flex w-full flex-row justify-center">
			<iframe
				class="aspect-video"
				src="https://www.youtube-nocookie.com/embed/0m60QbT85Tc?si=MCDnyVqz4aGggRrT"
				style="width: 100%; height: 100%"
				title="YouTube video player"
				frameborder="0"
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
				referrerpolicy="strict-origin-when-cross-origin"
				allowfullscreen
			></iframe>
		</div>
		<p>
			...in which he briefly displays a hypothetical "periodic table of game mechanics". The idea
			was really cool, and I saw some others who thought the same, like <a
				href="https://www.youtube.com/@MrEnvisioner"
				class="!text-on-surface-token"
				><u class="!decoration-primary-500 !decoration-2 !underline-offset-2">@Mr Envisioner</u></a
			>. I had a rudimentary idea on how to build it, so I tried. This is the result, a very hastily
			put-together prototype.
		</p>
		<img
			alt="A frame from a GMTK video on game mechanics, displaying a periodic table of game mechanics as elements"
			class="my-0 rounded-lg border border-primary-500"
			src="periodic_table_gmtk.png"
		/>
		<p class="w-full text-right text-xs">
			Credit: <YoutubeIcon class="mx-1 inline" /><a
				href="https://wikipedia.org/wiki/Game_mechanics"
				class="!decoration-primary-500 !decoration-2 !underline-offset-2 !text-on-surface-token"
				>Game Maker's Toolkit</a
			>
		</p>

		<h2 class="h2 text-primary-500">Using Mechdex</h2>
		<p>
			Mechdex is short for "mechanics index". It organizes modular, atomic <a
				href="https://wikipedia.org/wiki/Game_mechanics"
				class="!text-on-surface-token"
				><u class="!decoration-primary-500 !decoration-2 !underline-offset-2">game mechanics</u></a
			>, primarily those of video games. They're organised into 22 categories and are all
			searchable. Anyone can contribute to this database (see <i>Contributing a Mechanic</i>).
		</p>
		<p>
			The idea is that when you're stuck on a design problem, you can come here for inspiration, and
			to see what other designers did, how they solved it, and how well it worked.
		</p>
		<h2 class="h2 text-primary-500">This Is Very Scrappy</h2>
		<p>
			This project was made in a weekend by an absolute amateur, then worked on a little more over
			the course of three days. It's very minimal for now. This is not the final product. Please
			don't verbally abuse me. Thank you.
		</p>
		<h2 class="h2 text-primary-500">Regarding AI-Generated Content</h2>

		<p>
			The initial mechanics data was generated by AI. I'm very, very sorry to have had to do this,
			but there's no way I could write placeholders for 22x5 = 110 mechanics myself.
		</p>

		<p>You can see which ones are AI-generated with the this icon in the bottom-right corner:</p>

		<div class="variant-ghost-surface inline-block aspect-square place-items-center rounded-lg p-2">
			<HammerWrenchIcon class="ext-lg"></HammerWrenchIcon>
		</div>
		<p>
			These will be slowly phased out for human-written content. In the mean time, if you'd like to
			improve them, please do so!
		</p>
		<h2 class="h2 text-primary-500">Contributing a Mechanic</h2>
		<p>
			The entire database is stored in a Github repository. That's also why everything loads so
			slowly. Plans will eventually be made to move to better infrastructure.
		</p>
		<p>
			You can learn how to contribute <a href="/contribute" class="!text-on-surface-token"
				><u class="!decoration-primary-500 !decoration-2 !underline-offset-2">here</u></a
			>
			.
		</p>
	</article>
</div>
